services:
  - type: web
    name: asvix-fastapi
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api_server:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
